version: '3.8'

services:
  qbittorrent-monitor:
    image: milangeorge/qbittorrent-monitor:latest
    container_name: qbittorrent-monitor
    restart: unless-stopped
    user: "1001:1001" # apps user for TrueNAS
    environment:
      # First qBittorrent instance
      - QBITTORRENT_0_NAME=main
      - QBITTORRENT_0_URL=http://192.168.1.100:8080
      - QBITTORRENT_0_USERNAME=admin
      - QBITTORRENT_0_PASSWORD=adminadmin
      - QBITTORRENT_0_CHECK_INTERVAL=30
      # Connection timeout settings (in seconds)
      - QBITTORRENT_0_CONNECTION_TIMEOUT=60
      - QBITTORRENT_0_MAX_RETRIES=8
      - QBITTORRENT_0_RETRY_DELAY=15
      - QBITTORRENT_0_FOLDER_RETRY_DELAY=45 # Longer delay for folders
      # Second qBittorrent instance (optional)
      - QBITTORRENT_1_NAME=backup
      - QBITTORRENT_1_URL=http://192.168.1.101:8080
      - QBITTORRENT_1_USERNAME=admin
      - QBITTORRENT_1_PASSWORD=adminadmin
      - QBITTORRENT_1_CHECK_INTERVAL=45
      - QBITTORRENT_1_CONNECTION_TIMEOUT=60
      - QBITTORRENT_1_MAX_RETRIES=8
      - QBITTORRENT_1_RETRY_DELAY=15
      - QBITTORRENT_1_FOLDER_RETRY_DELAY=45
      # Global settings
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
